apiVersion: v1
kind: Service
metadata:
  name: orion-vision-core-service
  namespace: orion-vision-core
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: quantum
    port: 9090
    targetPort: 9090
  selector:
    app: orion-vision-core
  type: ClusterIP
