version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: orion-rabbitmq
    hostname: orion-rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: orion_admin
      RABBITMQ_DEFAULT_PASS: orion_secure_2024
      RABBITMQ_DEFAULT_VHOST: orion_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq:/etc/rabbitmq/conf.d
    networks:
      - orion_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  rabbitmq_data:
    driver: local

networks:
  orion_network:
    driver: bridge
