agents:
  cleanup_interval: 300
  enabled: true
  heartbeat_interval: 30
  log_level: INFO
  max_agents: 10
  registry_path: data/agent_registry.json
communication:
  grpc_enabled: true
  grpc_port: 50051
  rabbitmq_enabled: false
  rabbitmq_host: localhost
  rabbitmq_password: guest
  rabbitmq_port: 5672
  rabbitmq_user: guest
  websocket_enabled: true
  websocket_port: 8001
database:
  host: localhost
  name: orion.db
  password: ''
  path: data/orion.db
  port: 5432
  type: sqlite
  user: orion
gui:
  auto_open: false
  dashboard_port: 8502
  enabled: true
  streamlit_port: 8501
  theme: dark
logging:
  backup_count: 5
  console_output: true
  file_path: logs/orion.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
ollama:
  base_url: http://localhost:11434
  default_model: llama3.2:3b
  enabled: true
  host: localhost
  max_retries: 3
  port: 11434
  timeout: 30
security:
  allowed_origins: null
  enable_authentication: false
  enable_cors: true
  enable_rate_limiting: true
  max_requests_per_minute: 100
  secret_key: orion-secret-key-change-in-production
server:
  debug: false
  host: 0.0.0.0
  log_level: info
  port: 8000
  reload: false
  workers: 1
voice:
  channels: 1
  chunk_size: 1024
  enabled: true
  input_device: null
  output_device: null
  sample_rate: 16000
