base_path: "/home/orion/Masa\xFCst\xFC/Atlas"
cache_path: cache
component_integrator:
  auto_discovery: true
  auto_restart_failed: true
  discovery_paths:
  - jobone.vision_core.computer_access.vision
  - jobone.vision_core.quantum
  - jobone.vision_core.consciousness
  health_check_interval: 60.0
  lazy_loading: true
  load_timeout: 30.0
  parallel_loading: true
config_path: config
debug_mode: true
environment: development
graceful_degradation:
  auto_recovery_enabled: true
  component_timeout: 10.0
  error_threshold_critical: 10
  error_threshold_emergency: 20
  fallback_enabled: true
  health_check_interval: 60.0
  max_error_history: 1000
  recovery_timeout: 30.0
integration_bridge:
  cache_enabled: true
  display_available: true
  enable_q01_vision: true
  enable_q02_alt_las: true
  enable_q03_tasks: true
  enable_q04_ai: true
  enable_q05_quantum: true
  environment_type: hybrid
  graceful_degradation: true
  headless_fallback: true
  lazy_loading: true
  parallel_initialization: true
  retry_attempts: 3
  timeout_seconds: 30.0
logging:
  backup_count: 5
  console_level: INFO
  date_format: '%Y-%m-%d %H:%M:%S'
  error_log_file: logs/orion_errors.log
  file_level: DEBUG
  level: INFO
  log_file: logs/orion_vision_core.log
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_file_size: 10485760
logs_path: logs
unified_interface:
  api_key_required: false
  batch_size: 10
  batch_timeout: 1.0
  enable_authentication: false
  enable_metrics: true
  enable_request_batching: true
  max_concurrent_requests: 100
  metrics_interval: 60.0
  request_timeout: 30.0
  response_cache_size: 1000
version: 1.0.0
