version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: orion-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: orion
      RABBITMQ_DEFAULT_PASS: orion123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
    driver: local
